import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Aside from "@/components/Aside";
import Homepage from "@/components/Homepage";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
     title: "Create Next App",
     description: "Generated by create next app",
};

export default function RootLayout({
     children,
}: Readonly<{
     children: React.ReactNode;
}>) {
     return (
          <html lang="en">
               <body className={inter.className}>
                    <div className="mx-[250px]">
                         <Navbar />
                    </div>
                    <div className=" bg-gray-100">
                         <div className="mx-[250px] flex">
                              <Aside />
                              <div>
                                   <Homepage />
                              </div>
                         </div>
                    </div>
               </body>
          </html>
     );
}
